// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: ee6009393446f329a81cfa4b698ae10a)
declare namespace Cloudflare {
  interface Env {
    PORT: string
    ENVIRONMENT: string
    LOGGING: string
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string
}
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, 'PORT' | 'ENVIRONMENT' | 'LOGGING'>> {}
}
